source 'https://rubygems.org'
source 'https://BnrJb6FZyzspBboNJzYZ@gem.fury.io/govuk/'

gem 'cucumber', '1.3.8'
gem 'capybara', '2.1.0'
gem 'poltergeist', '1.4.1'
gem 'rspec', '2.14.1'
gem 'sass', '3.2.12'
gem 'parallel_tests', '0.15.0'
gem 'sauce', '3.2.0'
gem 'sauce-cucumber', '3.2.0'
gem 'sauce-connect', '3.2.0'
gem 'pry-debugger', '0.2.2'
